services:
  download_txt2img_model:
    image: sd-model-download:latest
    container_name: download_txt2img_model
    volumes:
      - ./stable-diffusion-models/models:/data/models
    build:
      context: ./stable-diffusion-models
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: &BASE_IMAGE bean980310/ubuntu-docker:1.0.5-cuda12.5.1-torch2.4.0
  # download_img2video_model:
  #   image: svd-model-download:latest
  #   container_name: download_img2video_model
  #   volumes:
  #     - ./stable-video-diffusion-models/models:/data/models
  #   build:
  #     context: ./stable-video-diffusion-models
  #     dockerfile: Dockerfile
  #     args:
  #       BASE_IMAGE: *BASE_IMAGE
  # download_txt23d_model:
  #   image: svd-model-download:latest
  #   container_name: download_txt23d_model
  #   volumes:
  #     - ./stable-zero123-models/models:/data/models
  #   build:
  #     context: ./stable-zero123-models
  #     dockerfile: Dockerfile
  #     args:
  #       BASE_IMAGE: *BASE_IMAGE