version: '3.9'

x-base_service: &base_service
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  restart: unless-stopped

services:
  stable-diffusion-webui:
    <<: *base_service
    profiles:
      - a1111-sdwebui
    image: bean980310/stable-diffusion-webui:latest
    volumes:
      - &models ./stable-diffusion-models/sd-models:/app/stable-diffusion-webui/models
      - &embeddings ./stable-diffusion-models/embeddings:/app/stable-diffusion-webui/embeddings
      - ./workspace/stable-diffusion-webui/extensions:/app/stable-diffusion-webui/extensions
      - ./workspace/stable-diffusion-webui/webui-user.sh:/app/stable-diffusion-webui/webui-user.sh
      - ./workspace/stable-diffusion-webui/config.json:/app/stable-diffusion-webui/config.json
      - ./outputs/stable-diffusion-webui:/app/stable-diffusion-webui/outputs
    ports:
      - "3010:7860"
    build:
      context: ./build/a1111-sdwebui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: &WEBUI_VERSION v1.9.4
        BASE_IMAGE: &base bean980310/ubuntu-docker:1.0.2-cuda-12.1.1-torch2.3.1
  kohya_ss:
    <<: *base_service
    profiles:
      - kohya_ss
    image: bean980310/kohya-ss:latest
    volumes:
      - ./stable-diffusion-models/sd-models:/app/kohya_ss/models
      - ./stable-diffusion-models/embeddings:/app/kohya_ss/models/embeddings
      - ./workspace/kohya_ss/accelerate.yaml:/app/accelerate.yaml
    ports:
      - "3020:7860"
    build:
      context: ./build/kohya_ss
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        KOHYA_VERSION: v24.1.4
  comfyui:
    <<: *base_service
    profiles:
      - comfyui
    image: bean980310/comfyui:latest
    volumes:
      - *models
      - *embeddings
      - ./workspace/ComfyUI/custom_nodes:/app/ComfyUI/custom_nodes
      - ./outputs/ComfyUI:/app/ComfyUI/output
    ports:
      - "3030:8188"
    build:
      context: ./build/comfyui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *base
        COMFYUI_COMMIT: 8e012043a9d0af3979bbe2cea8dc1ec7768f9d88
  invokeai:
    <<: *base_service
    profiles:
      - invokeai
    image: bean980310/invokeai:latest
    volumes:
      - type: bind
        source: ./workspace/InvokeAI
        target: /app/InvokeAI
        bind:
          create_host_path: true
      - ./stable-diffusion-models/sd-models:/app/data/models
      - ./stable-diffusion-models/embeddings:/app/data/embeddings
    ports:
      - "9090:9090"
    build:
      context: ./build/invokeai
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        INVOKEAI_VERSION: v4.2.4