x-base_service: &base_service
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  restart: unless-stopped

services:
  conda:
    <<: *base_service
    image: bean980310/conda:cu124
    build:
      context: ./build/base
      dockerfile: Dockerfile.conda
  nodejs:
    <<: *base_service
    image: bean980310/node:20
    build:
      context: ./build/base
      dockerfile: Dockerfile.nodejs
  dotnet:
    <<: *base_service
    image: bean980310/dotnet:8.0
    build:
      context: ./build/base
      dockerfile: Dockerfile.dotnet
  base:
    <<: *base_service
    image: bean980310/base:main
    build:
      context: ./build/base
      dockerfile: Dockerfile
      args:
        TORCH_VERSION: &TORCH_VERSION 2.5.1
        TORCH_CUDA_VERSION: &TORCH_CUDA_VERSION 12.4
        INDEX_URL: &INDEX_URL https://download.pytorch.org/whl/cu124
        XFORMERS_VERSION: &XFORMERS_VERSION 0.0.28.post3
  ollama:
    <<: *base_service
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: if_not_present
    tty: true
  stable-diffusion-webui: &stable-diffusion-webui
    <<: *base_service
    image: bean980310/stable-diffusion-webui:latest
    container_name: stable-diffusion-webui
    volumes:
      - stable-diffusion-webui:/app/stable-diffusion-webui
      - ./stable-diffusion-models/models/checkpoints:/app/stable-diffusion-webui/models/Stable-diffusion
      - ./stable-diffusion-models/models/clip:/app/stable-diffusion-webui/models/clip
      - ./stable-diffusion-models/models/clip_vision:/app/stable-diffusion-webui/models/clip-interrogator
      - ./stable-diffusion-models/models/configs:/app/stable-diffusion-webui/configs
      - ./stable-diffusion-models/models/controlnet:/app/stable-diffusion-webui/models/ControlNet
      - ./stable-diffusion-models/models/deepbooru:/app/stable-diffusion-webui/models/deepbooru
      - ./stable-diffusion-models/models/embeddings:/app/stable-diffusion-webui/embeddings
      - ./stable-diffusion-models/models/facerestore_models/Codeformer:/app/stable-diffusion-webui/models/Codeformer
      - ./stable-diffusion-models/models/facerestore_models/GFPGAN:/app/stable-diffusion-webui/models/GFPGAN
      - ./stable-diffusion-models/models/hypernetworks:/app/stable-diffusion-webui/models/hypernetworks
      - ./stable-diffusion-models/models/karlo:/app/stable-diffusion-webui/models/karlo
      - ./stable-diffusion-models/models/loras:/app/stable-diffusion-webui/models/Lora
      - ./stable-diffusion-models/models/sams:/app/stable-diffusion-webui/models/sam
      - ./stable-diffusion-models/models/ultralytics:/app/stable-diffusion-webui/models/adetailer
      - ./stable-diffusion-models/models/upscale_models/ESRGAN:/app/stable-diffusion-webui/models/ESRGAN
      - ./stable-diffusion-models/models/upscale_models/RealESRGAN:/app/stable-diffusion-webui/models/RealESRGAN
      - ./stable-diffusion-models/models/upscale_models/SwinIR:/app/stable-diffusion-webui/models/SwinIR
      - ./stable-diffusion-models/models/upscale_models/LDSR:/app/stable-diffusion-webui/models/LDSR
      - ./stable-diffusion-models/models/vae:/app/stable-diffusion-webui/models/VAE
      - ./stable-diffusion-models/models/vae_approx:/app/stable-diffusion-webui/models/VAE-approx
      - ./workspace/stable-diffusion-webui/.cache/huggingface:/app/stable-diffusion-webui/.cache/huggingface
      - ./workspace/stable-diffusion-webui/extensions:/app/stable-diffusion-webui/extensions
      - ./workspace/stable-diffusion-webui/webui-user.sh:/app/stable-diffusion-webui/webui-user.sh
      - ./workspace/stable-diffusion-webui/config.json:/app/stable-diffusion-webui/config.json
      - ./workspace/stable-diffusion-webui/ui-config.json:/app/stable-diffusion-webui/ui-config.json
      - ./outputs/stable-diffusion-webui:/app/stable-diffusion-webui/outputs
    ports:
      - "3010:7860"
    build:
      context: ./build/a1111-sdwebui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: &WEBUI_VERSION v1.10.1
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
  stable-diffusion-webui-runpod:
    <<: *stable-diffusion-webui
    image: bean980310/stable-diffusion-webui:runpod
    build:
      context: ./build/a1111-sdwebui
      dockerfile: Dockerfile.runpod
  kohya_ss:
    <<: *base_service
    image: bean980310/kohya-ss:latest
    container_name: kohya_ss
    volumes:
      - kohya_ss:/app/kohya_ss
      - ./stable-diffusion-models/models/checkpoints:/app/kohya_ss/models
      - ./workspace/kohya_ss/.cache/huggingface:/app/kohya_ss/.cache/huggingface
      - ./workspace/kohya_ss/dataset:/app/kohya_ss/dataset
      - ./workspace/kohya_ss/dataset/images:/app/kohya_ss/dataset/images
      - ./workspace/kohya_ss/dataset/logs:/app/kohya_ss/dataset/logs
      - ./workspace/kohya_ss/dataset/outputs:/app/kohya_ss/dataset/outputs
      - ./workspace/kohya_ss/dataset/regularization:/app/kohya_ss/dataset/regularization
      - ./workspace/kohya_ss/outputs:/app/kohya_ss/outputs
      - ./workspace/kohya_ss/accelerate.yaml:/ap/kohya_ss/accelerate.yaml
    ports:
      - "3020:7860"
    build:
      context: ./build/kohya_ss
      dockerfile: Dockerfile
      args:
        KOHYA_VERSION: v24.1.7
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
  comfyui:
    <<: *base_service
    image: bean980310/comfyui:latest
    container_name: comfyui
    volumes:
      - comfyui:/app/ComfyUI
      - ./stable-diffusion-models/models/checkpoints:/app/ComfyUI/models/checkpoints
      - ./stable-diffusion-models/models/clip:/app/ComfyUI/models/clip
      - ./stable-diffusion-models/models/clip_vision:/app/ComfyUI/models/clip_vision
      - ./stable-diffusion-models/models/configs:/app/ComfyUI/models/configs
      - ./stable-diffusion-models/models/controlnet:/app/ComfyUI/models/controlnet
      - ./stable-diffusion-models/models/diffusers:/app/ComfyUI/models/diffusers
      - ./stable-diffusion-models/models/embeddings:/app/ComfyUI/models/embeddings
      - ./stable-diffusion-models/models/gligen:/app/ComfyUI/models/gligen
      - ./stable-diffusion-models/models/hypernetworks:/app/ComfyUI/models/hypernetworks
      - ./stable-diffusion-models/models/loras:/app/ComfyUI/models/loras
      - ./stable-diffusion-models/models/mmdets:/app/ComfyUI/models/mmdets
      - ./stable-diffusion-models/models/onnx:/app/ComfyUI/models/onnx
      - ./stable-diffusion-models/models/photomaker:/app/ComfyUI/models/photomaker
      - ./stable-diffusion-models/models/sams:/app/ComfyUI/models/sams
      - ./stable-diffusion-models/models/style_models:/app/ComfyUI/models/style_models
      - ./stable-diffusion-models/models/ultralytics:/app/ComfyUI/models/ultralytics
      - ./stable-diffusion-models/models/unet:/app/ComfyUI/models/unet
      - ./stable-diffusion-models/models/upscale_models:/app/ComfyUI/modeos/upscale_models
      - ./stable-diffusion-models/models/vae:/app/ComfyUI/models/vae
      - ./stable-diffusion-models/models/vae_approx:/app/ComfyUI/models/vae_approx
      - ./workspace/ComfyUI/.cache/huggingface:/app/ComfyUI/.cache/huggingface
      - ./workspace/ComfyUI/custom_nodes:/app/ComfyUI/custom_nodes
      - ./workspace/ComfyUI/extra_model_paths.yaml:/app/ComfyUI/extra_model_paths.yaml
      - ./outputs/ComfyUI:/app/ComfyUI/output
    ports:
      - "3030:8188"
    build:
      context: ./build/comfyui
      dockerfile: Dockerfile
      args:
        COMFYUI_VERSION: &COMFYUI_VERSION v0.3.10
        WEBUI_VERSION: *WEBUI_VERSION
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
  invokeai:
    <<: *base_service
    image: bean980310/invokeai:latest
    container_name: invokeai
    volumes:
      - invokeai:/app/InvokeAI
      - ./stable-diffusion-models/models:/app/InvokeAI/models
      - ./workspace/InvokeAI/.cache/huggingface:/app/InvokeAI/.cache/huggingface
      - ./workspace/InvokeAI/custom_nodes:/app/InvokeAI/custom_nodes
      - ./workspace/InvokeAI/invokeai.yaml:/app/InvokeAI/invokeai.yaml
      - ./outputs/InvokeAI:/app/InvokeAI/outputs
    ports:
      - "9090:9090"
    build:
      context: ./build/invokeai
      dockerfile: Dockerfile
      args:
        INVOKEAI_VERSION: v5.5.0
        TORCH_VERSION: 2.4.1
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: https://download.pytorch.org/whl/cu124
        XFORMERS_VERSION: 0.0.28.post1
  open-webui:
    <<: *base_service
    image: bean980310/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/open-webui/backend/data
    ports:
      - "3000:8080"
    build:
      context: ./build/open-webui
      dockerfile: Dockerfile
      args:
        OLLAMA_BASE_URL: '/ollama'
        OPEN_WEBUI_VERSION: v0.5.2
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
  fooocus:
    <<: *base_service
    image: bean980310/fooocus:latest
    container_name: fooocus
    volumes:
      - fooocus-data:/app/Fooocus
      - ./stable-diffusion-models/models/checkpoints:/app/Fooocus/models/checkpoints
      - ./stable-diffusion-models/models/clip:/app/Fooocus/models/clip
      - ./stable-diffusion-models/models/clip_vision:/app/Fooocus/models/clip_vision
      - ./stable-diffusion-models/models/configs:/app/Fooocus/models/configs
      - ./stable-diffusion-models/models/controlnet:/app/Fooocus/models/controlnet
      - ./stable-diffusion-models/models/diffusers:/app/Fooocus/models/diffusers
      - ./stable-diffusion-models/models/embeddings:/app/Fooocus/models/embeddings
      - ./stable-diffusion-models/models/gligen:/app/Fooocus/models/gligen
      - ./stable-diffusion-models/models/hypernetworks:/app/Fooocus/models/hypernetworks
      - ./stable-diffusion-models/models/inpaint:/app/Fooocus/models/inpaint
      - ./stable-diffusion-models/models/loras:/app/Fooocus/models/loras
      - ./stable-diffusion-models/models/prompt_expansion:/app/Fooocus/models/prompt_expansion
      - ./stable-diffusion-models/models/safety_checker:/app/Fooocus/models/safety_checker
      - ./stable-diffusion-models/models/style_models:/app/Fooocus/models/style_models
      - ./stable-diffusion-models/models/unet:/app/Fooocus/models/unet
      - ./stable-diffusion-models/models/upscale_models:/app/Fooocus/models/upscale_models
      - ./stable-diffusion-models/models/vae:/app/Fooocus/models/vae
      - ./stable-diffusion-models/models/vae_approx:/app/Fooocus/models/vae_approx
      - ./workspace/Fooocus/.cache/huggingface:/app/Fooocus/.cache/huggingface
      - ./workspace/Fooocus/config.txt:/app/Fooocus/config.txt
      - ./outputs/Fooocus:/app/Fooocus/outputs
    ports:
      - "3040:7860"
    build:
      context: ./build/fooocus
      dockerfile: Dockerfile
      args:
        FOOOCUS_VERSION: v2.5.5
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
  sdnext:
    <<: *base_service
    image: bean980310/sdnext:latest
    container_name: sdnext
    volumes:
      - sdnext:/app/automatic
      - ./stable-diffusion-models/models:/app/automatic/models
      - ./stable-diffusion-models/models/configs:/app/automatic/configs
      - ./stable-diffusion-models/models/vae_approx:/app/automatic/models/VAE-approx
      - ./workspace/SD.Next/.cache/huggingface:/app/automatic/.cache/huggingface
      - ./workspace/SD.Next/extensions:/app/automatic/extensions
      - ./workspace/SD.Next/config.json:/app/automatic/config.json
      - ./workspace/SD.Next/ui-config.json:/app/automatic/ui-config.json
      - ./outputs/SD.Next:/app/automatic/outputs
    ports:
      - "3060:7860"
    build:
      context: ./build/vladmandic-sdnext
      dockerfile: Dockerfile
      args:
        SDNEXT_COMMIT: master
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
  swarmui:
    <<: *base_service
    image: bean980310/swarmui:latest
    container_name: swarmui
    volumes:
      - swarmdata:/app/SwarmUI/Data
      - swarmbackend:/app/SwarmUI/dlbackend
      - swarmui:/app/SwarmUI
      - ./stable-diffusion-models/models:/app/SwarmUI/Models
      - ./workspace/SwarmUI/.cache/huggingface:/app/SwarmUI/.cache/huggingface
      - ./outputs/SwarmUI:/app/SwarmUI/Output
    ports:
      - "7801:7801"
    build:
      context: ./build/swarmui
      dockerfile: Dockerfile
      args:
        SWARMUI_VERSION: 0.9.4-Beta
        COMFYUI_VERSION: *COMFYUI_VERSION
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
    environment:
      - SWARM_NO_VENV='true'
  facefusion:
    <<: *base_service
    image: bean980310/facefusion:latest
    container_name: facefusion
    volumes:
      - facefusion:/app/facefusion
      - ./workspace/facefusion/.assets:/app/facefusion/.assets
      - ./workspace/facefusion/.cache/huggingface:/app/facefusion/.cache/huggingface
    ports:
      - "3070:7860"
    build:
      context: ./build/facefusion
      dockerfile: Dockerfile
      args:
        FACEFUSION_VERSION: 3.1.0
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
  # stable-audio-tools:
  #   <<: *base_service
  #   image: bean980310/stable-audio-tools:latest
  #   container_name: stable-audio-tools
  #   volumes:
  #     - stable-audio-tools:/app/stable-audio-tools
  #     - ./stable-audio-models/models:/app/stable-audio-tools/models
  #     - ./workspace/stable-audio-models/.cache/huggingface:/app/stable-audio-models/.cache/huggingface
  #   ports:
  #     - "3090:7860"
  #   build:
  #     context: ./build/stable-audio-tools
  #     dockerfile: Dockerfile
  #     args:
  #       STABLE_AUDIO_TOOLS_COMMIT: main
  #       TORCH_VERSION: *TORCH_VERSION
  #       TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
  #       INDEX_URL: *INDEX_URL
  #       XFORMERS_VERSION: *XFORMERS_VERSION
  #   environment:
  #     - GRADIO_SERVER_NAME=0.0.0.0
  #     - GRADIO_SERVER_PORT=7860
  audiocraft_plus:
    <<: *base_service
    image: bean980310/audiocraft-plus:latest
    container_name: audiocraft_plus
    volumes:
      - audiocraft_plus:/app/audiocraft_plus
      - ./audiocraft-models/models:/app/audiocraft_plus/models
      - ./workspace/audiocraft_plus/.cache/huggingface:/app/audiocraft_plus/.cache/huggingface
    ports:
      - "7877:7877"
    build:
      context: ./build/audiocraft_plus
      dockerfile: Dockerfile
      args:
        TORCH_VERSION: *TORCH_VERSION
        TORCH_CUDA_VERSION: *TORCH_CUDA_VERSION
        INDEX_URL: *INDEX_URL
        XFORMERS_VERSION: *XFORMERS_VERSION

volumes:
  ollama:
  open-webui:
  stable-diffusion-webui:
  comfyui:
  kohya_ss:
  invokeai:
  fooocus-data:
  sdnext:
  swarmui:
  swarmdata:
  swarmbackend:
  facefusion:
  stable-audio-tools:
  audiocraft_plus: