x-base_service: &base_service
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  restart: unless-stopped

services:
  conda:
    <<: *base_service
    image: bean980310/conda:cu124
    build:
      context: ./build/base
      dockerfile: Dockerfile.conda
  nodejs:
    <<: *base_service
    image: bean980310/node:20
    build:
      context: ./build/base
      dockerfile: Dockerfile.nodejs