services:
  download_model:
    image: bean980310/sd-model-download:latest
    container_name: download_model
    volumes:
      - ./stable-diffusion-models/models:/data/models
      - ./stable-diffusion-models/embeddings:/data/embeddings
    build:
      context: ./stable-diffusion-models
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: bean980310/ubuntu-docker:1.0.2-cuda12.1.1-torch2.3.1