version: '3.9'

x-base_service: &base_service
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
  restart: unless-stopped

services:
  stable-diffusion-webui:
    <<: *base_service
    image: bean980310/stable-diffusion-webui:latest
    container_name: stable-diffusion-webui
    volumes:
      - &models ./stable-diffusion-models/sd-models:/app/stable-diffusion-webui/models
      - &embeddings ./stable-diffusion-models/embeddings:/app/stable-diffusion-webui/embeddings
      - ./workspace/stable-diffusion-webui/extensions:/app/stable-diffusion-webui/extensions
      - ./workspace/stable-diffusion-webui/webui-user.sh:/app/stable-diffusion-webui/webui-user.sh
      - ./workspace/stable-diffusion-webui/config.json:/app/stable-diffusion-webui/config.json
      - ./workspace/stable-diffusion-webui/ui-config.json:/app/stable-diffusion-webui/ui-config.json
      - ./outputs/stable-diffusion-webui:/app/stable-diffusion-webui/outputs
    ports:
      - "3010:7860"
    build:
      context: ./build/a1111-sdwebui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: &WEBUI_VERSION v1.9.4
        BASE_IMAGE: &BASE_IMAGE bean980310/ubuntu-docker:1.0.2-cuda12.1.1-torch2.3.1
  kohya_ss:
    <<: *base_service
    image: bean980310/kohya-ss:latest
    container_name: kohya_ss
    volumes:
      - ./stable-diffusion-models/sd-models:/app/kohya_ss/models
      - ./stable-diffusion-models/embeddings:/app/kohya_ss/models/embeddings
      - ./workspace/kohya_ss/dataset:/app/kohya_ss/dataset
      - ./workspace/kohya_ss/accelerate.yaml:/app/accelerate.yaml
    ports:
      - "3020:7860"
    build:
      context: ./build/kohya_ss
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        KOHYA_VERSION: v24.1.4
  comfyui:
    <<: *base_service
    image: bean980310/comfyui:latest
    container_name: comfyui
    volumes:
      - *models
      - *embeddings
      - ./workspace/ComfyUI/custom_nodes:/app/ComfyUI/custom_nodes
      - ./workspace/ComfyUI/extra_model_paths.yaml:/app/ComfyUI/extra_model_paths.yaml
      - ./outputs/ComfyUI:/app/ComfyUI/output
    ports:
      - "3030:8188"
    build:
      context: ./build/comfyui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        COMFYUI_COMMIT: 4ca9b9cc29fefaa899cba67d61a8252ae9f16c0d
        COMFYUI_VERSION: &COMFYUI_VERSION v0.0.1
  invokeai:
    <<: *base_service
    image: bean980310/invokeai:latest
    container_name: invokeai
    volumes:
      - ./stable-diffusion-models/sd-models:/app/InvokeAI/models
      - ./stable-diffusion-models/embeddings:/app/InvokeAI/models/embeddings
      - ./workspace/InvokeAI/custom_nodes:/app/InvokeAI/custom_nodes
      - ./workspace/InvokeAI/invokeai.yaml:/app/InvokeAI/invokeai.yaml
      - ./outputs/InvokeAI:/app/InvokeAI/outputs
    ports:
      - "9090:9090"
    build:
      context: ./build/invokeai
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        INVOKEAI_VERSION: v4.2.4
  fooocus:
    <<: *base_service
    image: bean980310/fooocus:latest
    container_name: fooocus
    volumes:
      - ./stable-diffusion-models/sd-models/Stable-diffusion:/app/Fooocus/models/checkpoints
      - ./stable-diffusion-models/sd-models/Lora:/app/Fooocus/models/loras
      - ./stable-diffusion-models/embeddings:/app/Fooocus/models/embeddings
      - ./stable-diffusion-models/sd-models/vae_approx:/app/Fooocus/models/vae_approx
      - ./stable-diffusion-models/sd-models/ESRGAN:/app/Fooocus/models/upscale_models
      - ./stable-diffusion-models/sd-models/RealESRGAN:/app/Fooocus/models/upscale_models
      - ./stable-diffusion-models/sd-models/ControlNet:/app/Fooocus/models/controlnet
      - ./stable-diffusion-models/sd-models/clip-interrogator:/app/Fooocus/models/clip_vision
      - ./outputs/Fooocus:/app/Fooocus/outputs
    ports:
      - "3040:7860"
    build:
      context: ./build/fooocus
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        FOOOCUS_VERSION: v2.4.3
    # environment:
    #   - PRESET=anime
    #   - PRESET=realistic
  stable-diffusion-webui-forge:
    <<: *base_service
    image: bean980310/stable-diffusion-webui-forge:latest
    container_name: stable-diffusion-webui-forge
    volumes:
      - ./stable-diffusion-models/sd-models:/app/stable-diffusion-webui-forge/models
      - ./stable-diffusion-models/embeddings:/app/stable-diffusion-webui-forge/embeddings
      - ./workspace/stable-diffusion-webui-forge/extensions:/app/stable-diffusion-webui-forge/extensions
      - ./workspace/stable-diffusion-webui-forge/webui-user.sh:/app/stable-diffusion-webui-forge/webui-user.sh
      - ./workspace/stable-diffusion-webui-forge/config.json:/app/stable-diffusion-webui-forge/config.json
      - ./workspace/stable-diffusion-webui-forge/ui-config.json:/app/stable-diffusion-webui-forge/ui-config.json
      - ./outputs/stable-diffusion-webui-forge:/app/stable-diffusion-webui-forge/outputs
    ports:
      - "3050:7860"
    build:
      context: ./build/sdwebui-forge
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        FORGE_COMMIT: bfee03d8d9415a925616f40ede030fe7a51cbcfd
  sdnext:
    <<: *base_service
    image: bean980310/sdnext:latest
    container_name: sdnext
    volumes:
      - ./stable-diffusion-models/sd-models:/app/automatic/models
      - ./stable-diffusion-models/embeddings:/app/automatic/models/embeddings
      - ./workspace/SD.Next/extensions:/app/automatic/extensions
      - ./workspace/SD.Next/config.json:/app/automatic/config.json
      - ./workspace/SD.Next/ui-config.json:/app/automatic/ui-config.json
      - ./outputs/SD.Next:/app/automatic/outputs
    ports:
      - "3060:7860"
    build:
      context: ./build/vladmandic-sdnext
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        SDNEXT_COMMIT: 2ec6e9eec481223b8abe50cb5165d5fd9be2d086
  easy-diffusion:
    <<: *base_service
    image: bean980310/easy-diffusion:latest
    container_name: easy-diffusion
    volumes:
      - ./stable-diffusion-models/sd-models:/app/easy-diffusion/models
      - ./stable-diffusion-models/embeddings:/app/easy-diffusion/models/embeddings
      - ./workspace/easy-diffusion/config.yaml:/app/easy-diffusion/config.yaml
      - ./outputs/easy-diffusion:/app/easy-diffusion/outputs
    ports:
      - "9000:9000"
    build:
      context: ./build/easy-diffusion
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        EASYDIFF_VERSION: v3.0.2
  swarmui:
    <<: *base_service
    image: bean980310/swarmui:latest
    container_name: swarmui
    volumes:
      - swarmdata:/app/SwarmUI/Data
      - swarmbackend:/app/SwarmUI/dlbackend
      - ./stable-diffusion-models/sd-models:/app/SwarmUI/Models
      - ./stable-diffusion-models/embeddings:/app/SwarmUI/Models/embeddings
      - ./outputs/SwarmUI:/app/SwarmUI/Output
    ports:
      - "7801:7801"
    build:
      context: ./build/swarmui
      dockerfile: Dockerfile
      args:
        WEBUI_VERSION: *WEBUI_VERSION
        BASE_IMAGE: *BASE_IMAGE
        SWARMUI_VERSION: 0.9.1-Beta
        COMFYUI_VERSION: *COMFYUI_VERSION