name: Checkout

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Add & Commit
              uses: EndBug/add-and-commit@v9.1.4
          
            